// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: risk/v1/risk.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// //
type RiskTx struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contract string `protobuf:"bytes,1,opt,name=Contract,proto3" json:"Contract,omitempty" v:"required"` // v: required
	TxData   string `protobuf:"bytes,2,opt,name=TxData,proto3" json:"TxData,omitempty" v:"required"`     // v: required
}

func (x *RiskTx) Reset() {
	*x = RiskTx{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiskTx) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskTx) ProtoMessage() {}

func (x *RiskTx) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskTx.ProtoReflect.Descriptor instead.
func (*RiskTx) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{0}
}

func (x *RiskTx) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *RiskTx) GetTxData() string {
	if x != nil {
		return x.TxData
	}
	return ""
}

type TxRiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty" v:"required"`   // v: required
	Address string `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty" v:"required"` // v: required
	// //
	Txs []*RiskTx `protobuf:"bytes,3,rep,name=Txs,proto3" json:"Txs,omitempty" dc:"//" v:"required"` // v: required
}

func (x *TxRiskReq) Reset() {
	*x = TxRiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskReq) ProtoMessage() {}

func (x *TxRiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskReq.ProtoReflect.Descriptor instead.
func (*TxRiskReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{1}
}

func (x *TxRiskReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TxRiskReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TxRiskReq) GetTxs() []*RiskTx {
	if x != nil {
		return x.Txs
	}
	return nil
}

type TxRiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok         int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RiskSerial string `protobuf:"bytes,3,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"`
}

func (x *TxRiskRes) Reset() {
	*x = TxRiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskRes) ProtoMessage() {}

func (x *TxRiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskRes.ProtoReflect.Descriptor instead.
func (*TxRiskRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{2}
}

func (x *TxRiskRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TxRiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TxRiskRes) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

// //
type TFARiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     string `protobuf:"bytes,1,opt,name=UserId,proto3" json:"UserId,omitempty" v:"required"`         // v: required
	Operations string `protobuf:"bytes,2,opt,name=Operations,proto3" json:"Operations,omitempty" v:"required"` // v: required
}

func (x *TFARiskReq) Reset() {
	*x = TFARiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskReq) ProtoMessage() {}

func (x *TFARiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskReq.ProtoReflect.Descriptor instead.
func (*TFARiskReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{3}
}

func (x *TFARiskReq) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TFARiskReq) GetOperations() string {
	if x != nil {
		return x.Operations
	}
	return ""
}

type TFARiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok         int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg        string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	RiskSerial string `protobuf:"bytes,3,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty"`
}

func (x *TFARiskRes) Reset() {
	*x = TFARiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskRes) ProtoMessage() {}

func (x *TFARiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskRes.ProtoReflect.Descriptor instead.
func (*TFARiskRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{4}
}

func (x *TFARiskRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *TFARiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *TFARiskRes) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

type SmsCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty" v:"required"` // v: required
	Operations string `protobuf:"bytes,2,opt,name=Operations,proto3" json:"Operations,omitempty" v:"required"` // v: required
}

func (x *SmsCodeReq) Reset() {
	*x = SmsCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeReq) ProtoMessage() {}

func (x *SmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeReq.ProtoReflect.Descriptor instead.
func (*SmsCodeReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{5}
}

func (x *SmsCodeReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *SmsCodeReq) GetOperations() string {
	if x != nil {
		return x.Operations
	}
	return ""
}

type SmsCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *SmsCodeRes) Reset() {
	*x = SmsCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeRes) ProtoMessage() {}

func (x *SmsCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeRes.ProtoReflect.Descriptor instead.
func (*SmsCodeRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{6}
}

func (x *SmsCodeRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *SmsCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MailCodekReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty" v:"required"` // v: required
	Operations string `protobuf:"bytes,2,opt,name=Operations,proto3" json:"Operations,omitempty" v:"required"` // v: required
}

func (x *MailCodekReq) Reset() {
	*x = MailCodekReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailCodekReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodekReq) ProtoMessage() {}

func (x *MailCodekReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodekReq.ProtoReflect.Descriptor instead.
func (*MailCodekReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{7}
}

func (x *MailCodekReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *MailCodekReq) GetOperations() string {
	if x != nil {
		return x.Operations
	}
	return ""
}

type MailCodekRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *MailCodekRes) Reset() {
	*x = MailCodekRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailCodekRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodekRes) ProtoMessage() {}

func (x *MailCodekRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodekRes.ProtoReflect.Descriptor instead.
func (*MailCodekRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{8}
}

func (x *MailCodekRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *MailCodekRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ///
type VerifyCodekReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RiskSerial string `protobuf:"bytes,1,opt,name=RiskSerial,proto3" json:"RiskSerial,omitempty" v:"required"` // v: required
	Code       string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty" v:"required"`             // v: required
}

func (x *VerifyCodekReq) Reset() {
	*x = VerifyCodekReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodekReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodekReq) ProtoMessage() {}

func (x *VerifyCodekReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodekReq.ProtoReflect.Descriptor instead.
func (*VerifyCodekReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{9}
}

func (x *VerifyCodekReq) GetRiskSerial() string {
	if x != nil {
		return x.RiskSerial
	}
	return ""
}

func (x *VerifyCodekReq) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type VerifyCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  int32  `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *VerifyCodeRes) Reset() {
	*x = VerifyCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCodeRes) ProtoMessage() {}

func (x *VerifyCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCodeRes.ProtoReflect.Descriptor instead.
func (*VerifyCodeRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{10}
}

func (x *VerifyCodeRes) GetOk() int32 {
	if x != nil {
		return x.Ok
	}
	return 0
}

func (x *VerifyCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_risk_v1_risk_proto protoreflect.FileDescriptor

var file_risk_v1_risk_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x69, 0x73, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3c, 0x0a, 0x06, 0x52, 0x69, 0x73, 0x6b, 0x54,
	0x78, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x54, 0x78, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54,
	0x78, 0x44, 0x61, 0x74, 0x61, 0x22, 0x5d, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x03, 0x54, 0x78, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0c, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x78, 0x52,
	0x03, 0x54, 0x78, 0x73, 0x22, 0x4d, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f,
	0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72,
	0x69, 0x61, 0x6c, 0x22, 0x44, 0x0a, 0x0a, 0x54, 0x46, 0x41, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65,
	0x71, 0x12, 0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x4e, 0x0a, 0x0a, 0x54, 0x46, 0x41,
	0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52,
	0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x22, 0x4c, 0x0a, 0x0a, 0x53, 0x6d, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2e, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x4e, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x43,
	0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x52, 0x69, 0x73,
	0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x30, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x43,
	0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x0e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a, 0x0a, 0x52,
	0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x52, 0x69, 0x73, 0x6b, 0x53, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x43,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0x31, 0x0a, 0x0d, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4f, 0x6b,
	0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d,
	0x73, 0x67, 0x32, 0xed, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0c, 0x50,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x34, 0x0a,
	0x0e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x78, 0x73, 0x12,
	0x0f, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71,
	0x1a, 0x0f, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x69,
	0x73, 0x6b, 0x54, 0x46, 0x41, 0x12, 0x10, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x46, 0x41,
	0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54,
	0x46, 0x41, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e, 0x50,
	0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x2e,
	0x72, 0x69, 0x73, 0x6b, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x3b, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x4d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x4d, 0x61,
	0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x72, 0x69, 0x73,
	0x6b, 0x2e, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x40, 0x0a, 0x11, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x79, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x72, 0x69,
	0x73, 0x6b, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73,
	0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2f, 0x76, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_risk_v1_risk_proto_rawDescOnce sync.Once
	file_risk_v1_risk_proto_rawDescData = file_risk_v1_risk_proto_rawDesc
)

func file_risk_v1_risk_proto_rawDescGZIP() []byte {
	file_risk_v1_risk_proto_rawDescOnce.Do(func() {
		file_risk_v1_risk_proto_rawDescData = protoimpl.X.CompressGZIP(file_risk_v1_risk_proto_rawDescData)
	})
	return file_risk_v1_risk_proto_rawDescData
}

var file_risk_v1_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_risk_v1_risk_proto_goTypes = []interface{}{
	(*RiskTx)(nil),         // 0: risk.RiskTx
	(*TxRiskReq)(nil),      // 1: risk.TxRiskReq
	(*TxRiskRes)(nil),      // 2: risk.TxRiskRes
	(*TFARiskReq)(nil),     // 3: risk.TFARiskReq
	(*TFARiskRes)(nil),     // 4: risk.TFARiskRes
	(*SmsCodeReq)(nil),     // 5: risk.SmsCodeReq
	(*SmsCodeRes)(nil),     // 6: risk.SmsCodeRes
	(*MailCodekReq)(nil),   // 7: risk.MailCodekReq
	(*MailCodekRes)(nil),   // 8: risk.MailCodekRes
	(*VerifyCodekReq)(nil), // 9: risk.VerifyCodekReq
	(*VerifyCodeRes)(nil),  // 10: risk.VerifyCodeRes
	(*empty.Empty)(nil),    // 11: google.protobuf.Empty
}
var file_risk_v1_risk_proto_depIdxs = []int32{
	0,  // 0: risk.TxRiskReq.Txs:type_name -> risk.RiskTx
	11, // 1: risk.User.PerformAlive:input_type -> google.protobuf.Empty
	1,  // 2: risk.User.PerformRiskTxs:input_type -> risk.TxRiskReq
	3,  // 3: risk.User.PerformRiskTFA:input_type -> risk.TFARiskReq
	5,  // 4: risk.User.PerformSmsCode:input_type -> risk.SmsCodeReq
	7,  // 5: risk.User.PerformMailCode:input_type -> risk.MailCodekReq
	9,  // 6: risk.User.PerformVerifyCode:input_type -> risk.VerifyCodekReq
	11, // 7: risk.User.PerformAlive:output_type -> google.protobuf.Empty
	2,  // 8: risk.User.PerformRiskTxs:output_type -> risk.TxRiskRes
	4,  // 9: risk.User.PerformRiskTFA:output_type -> risk.TFARiskRes
	6,  // 10: risk.User.PerformSmsCode:output_type -> risk.SmsCodeRes
	8,  // 11: risk.User.PerformMailCode:output_type -> risk.MailCodekRes
	10, // 12: risk.User.PerformVerifyCode:output_type -> risk.VerifyCodeRes
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_risk_v1_risk_proto_init() }
func file_risk_v1_risk_proto_init() {
	if File_risk_v1_risk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_risk_v1_risk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiskTx); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailCodekReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailCodekRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodekReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_risk_v1_risk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_v1_risk_proto_goTypes,
		DependencyIndexes: file_risk_v1_risk_proto_depIdxs,
		MessageInfos:      file_risk_v1_risk_proto_msgTypes,
	}.Build()
	File_risk_v1_risk_proto = out.File
	file_risk_v1_risk_proto_rawDesc = nil
	file_risk_v1_risk_proto_goTypes = nil
	file_risk_v1_risk_proto_depIdxs = nil
}
