// protoc --go_out=plugins=grpc:. *.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: risk/v1/risk.proto

package v1

import (
	reflect "reflect"
	sync "sync"

	empty "github.com/golang/protobuf/ptypes/empty"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxRiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address  string `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty" v:"required"`   // v: required
	Contract string `protobuf:"bytes,2,opt,name=Contract,proto3" json:"Contract,omitempty" v:"required"` // v: required
	// //
	TxData string `protobuf:"bytes,3,opt,name=TxData,proto3" json:"TxData,omitempty" dc:"//" v:"required"` // v: required
}

func (x *TxRiskReq) Reset() {
	*x = TxRiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskReq) ProtoMessage() {}

func (x *TxRiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskReq.ProtoReflect.Descriptor instead.
func (*TxRiskReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{0}
}

func (x *TxRiskReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TxRiskReq) GetContract() string {
	if x != nil {
		return x.Contract
	}
	return ""
}

func (x *TxRiskReq) GetTxData() string {
	if x != nil {
		return x.TxData
	}
	return ""
}

type TxRiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *TxRiskRes) Reset() {
	*x = TxRiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxRiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxRiskRes) ProtoMessage() {}

func (x *TxRiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxRiskRes.ProtoReflect.Descriptor instead.
func (*TxRiskRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{1}
}

func (x *TxRiskRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TxRiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// //
type TFARiskReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty" v:"required"` // v: required
}

func (x *TFARiskReq) Reset() {
	*x = TFARiskReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskReq) ProtoMessage() {}

func (x *TFARiskReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskReq.ProtoReflect.Descriptor instead.
func (*TFARiskReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{2}
}

func (x *TFARiskReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type TFARiskRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok  bool   `protobuf:"varint,1,opt,name=Ok,proto3" json:"Ok,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *TFARiskRes) Reset() {
	*x = TFARiskRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TFARiskRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TFARiskRes) ProtoMessage() {}

func (x *TFARiskRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TFARiskRes.ProtoReflect.Descriptor instead.
func (*TFARiskRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{3}
}

func (x *TFARiskRes) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *TFARiskRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type SmsCodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty" v:"required"`           // v: required
	Operations string `protobuf:"bytes,2,opt,name=Operations,proto3" json:"Operations,omitempty" v:"required"` // v: required
}

func (x *SmsCodeReq) Reset() {
	*x = SmsCodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeReq) ProtoMessage() {}

func (x *SmsCodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeReq.ProtoReflect.Descriptor instead.
func (*SmsCodeReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{4}
}

func (x *SmsCodeReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SmsCodeReq) GetOperations() string {
	if x != nil {
		return x.Operations
	}
	return ""
}

type SmsCodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *SmsCodeRes) Reset() {
	*x = SmsCodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SmsCodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SmsCodeRes) ProtoMessage() {}

func (x *SmsCodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SmsCodeRes.ProtoReflect.Descriptor instead.
func (*SmsCodeRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{5}
}

func (x *SmsCodeRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SmsCodeRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type MailCodekReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token      string `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty" v:"required"`           // v: required
	Operations string `protobuf:"bytes,2,opt,name=Operations,proto3" json:"Operations,omitempty" v:"required"` // v: required
}

func (x *MailCodekReq) Reset() {
	*x = MailCodekReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailCodekReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodekReq) ProtoMessage() {}

func (x *MailCodekReq) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodekReq.ProtoReflect.Descriptor instead.
func (*MailCodekReq) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{6}
}

func (x *MailCodekReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MailCodekReq) GetOperations() string {
	if x != nil {
		return x.Operations
	}
	return ""
}

type MailCodekRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id  string `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Msg string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *MailCodekRes) Reset() {
	*x = MailCodekRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_risk_v1_risk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MailCodekRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MailCodekRes) ProtoMessage() {}

func (x *MailCodekRes) ProtoReflect() protoreflect.Message {
	mi := &file_risk_v1_risk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MailCodekRes.ProtoReflect.Descriptor instead.
func (*MailCodekRes) Descriptor() ([]byte, []int) {
	return file_risk_v1_risk_proto_rawDescGZIP(), []int{7}
}

func (x *MailCodekRes) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MailCodekRes) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_risk_v1_risk_proto protoreflect.FileDescriptor

var file_risk_v1_risk_proto_rawDesc = []byte{
	0x0a, 0x12, 0x72, 0x69, 0x73, 0x6b, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x72, 0x69, 0x73, 0x6b, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x59, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x69, 0x73,
	0x6b, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a,
	0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x78,
	0x44, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x78, 0x44, 0x61,
	0x74, 0x61, 0x22, 0x2d, 0x0a, 0x09, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x4f, 0x6b, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x22, 0x22, 0x0a, 0x0a, 0x54, 0x46, 0x41, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x2e, 0x0a, 0x0a, 0x54, 0x46, 0x41, 0x52, 0x69, 0x73, 0x6b,
	0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x4f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x4f, 0x6b, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x42, 0x0a, 0x0a, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f,
	0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x2e, 0x0a, 0x0a, 0x53, 0x6d, 0x73,
	0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x22, 0x44, 0x0a, 0x0c, 0x4d, 0x61, 0x69,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22,
	0x30, 0x0a, 0x0c, 0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x12,
	0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x64, 0x12,
	0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73,
	0x67, 0x32, 0xaa, 0x02, 0x0a, 0x04, 0x55, 0x73, 0x65, 0x72, 0x12, 0x40, 0x0a, 0x0c, 0x50, 0x65,
	0x72, 0x66, 0x6f, 0x72, 0x6d, 0x41, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x33, 0x0a, 0x0d,
	0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x69, 0x73, 0x6b, 0x54, 0x78, 0x12, 0x0f, 0x2e,
	0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x78, 0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x36, 0x0a, 0x0e, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x52, 0x69, 0x73, 0x6b,
	0x54, 0x46, 0x41, 0x12, 0x10, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x46, 0x41, 0x52, 0x69,
	0x73, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x54, 0x46, 0x41,
	0x52, 0x69, 0x73, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x0e, 0x50, 0x65, 0x72,
	0x66, 0x6f, 0x72, 0x6d, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x2e, 0x72, 0x69,
	0x73, 0x6b, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e,
	0x72, 0x69, 0x73, 0x6b, 0x2e, 0x53, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22,
	0x00, 0x12, 0x3b, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x66, 0x6f, 0x72, 0x6d, 0x4d, 0x61, 0x69, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e, 0x4d, 0x61, 0x69, 0x6c,
	0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x72, 0x69, 0x73, 0x6b, 0x2e,
	0x4d, 0x61, 0x69, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x0a,
	0x5a, 0x08, 0x2f, 0x72, 0x69, 0x73, 0x6b, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_risk_v1_risk_proto_rawDescOnce sync.Once
	file_risk_v1_risk_proto_rawDescData = file_risk_v1_risk_proto_rawDesc
)

func file_risk_v1_risk_proto_rawDescGZIP() []byte {
	file_risk_v1_risk_proto_rawDescOnce.Do(func() {
		file_risk_v1_risk_proto_rawDescData = protoimpl.X.CompressGZIP(file_risk_v1_risk_proto_rawDescData)
	})
	return file_risk_v1_risk_proto_rawDescData
}

var file_risk_v1_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_risk_v1_risk_proto_goTypes = []interface{}{
	(*TxRiskReq)(nil),    // 0: risk.TxRiskReq
	(*TxRiskRes)(nil),    // 1: risk.TxRiskRes
	(*TFARiskReq)(nil),   // 2: risk.TFARiskReq
	(*TFARiskRes)(nil),   // 3: risk.TFARiskRes
	(*SmsCodeReq)(nil),   // 4: risk.SmsCodeReq
	(*SmsCodeRes)(nil),   // 5: risk.SmsCodeRes
	(*MailCodekReq)(nil), // 6: risk.MailCodekReq
	(*MailCodekRes)(nil), // 7: risk.MailCodekRes
	(*empty.Empty)(nil),  // 8: google.protobuf.Empty
}
var file_risk_v1_risk_proto_depIdxs = []int32{
	8, // 0: risk.User.PerformAlive:input_type -> google.protobuf.Empty
	0, // 1: risk.User.PerformRiskTx:input_type -> risk.TxRiskReq
	2, // 2: risk.User.PerformRiskTFA:input_type -> risk.TFARiskReq
	4, // 3: risk.User.PerformSmsCode:input_type -> risk.SmsCodeReq
	6, // 4: risk.User.PerformMailCode:input_type -> risk.MailCodekReq
	8, // 5: risk.User.PerformAlive:output_type -> google.protobuf.Empty
	1, // 6: risk.User.PerformRiskTx:output_type -> risk.TxRiskRes
	3, // 7: risk.User.PerformRiskTFA:output_type -> risk.TFARiskRes
	5, // 8: risk.User.PerformSmsCode:output_type -> risk.SmsCodeRes
	7, // 9: risk.User.PerformMailCode:output_type -> risk.MailCodekRes
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_risk_v1_risk_proto_init() }
func file_risk_v1_risk_proto_init() {
	if File_risk_v1_risk_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_risk_v1_risk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxRiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TFARiskRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SmsCodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailCodekReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_risk_v1_risk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MailCodekRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_risk_v1_risk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_risk_v1_risk_proto_goTypes,
		DependencyIndexes: file_risk_v1_risk_proto_depIdxs,
		MessageInfos:      file_risk_v1_risk_proto_msgTypes,
	}.Build()
	File_risk_v1_risk_proto = out.File
	file_risk_v1_risk_proto_rawDesc = nil
	file_risk_v1_risk_proto_goTypes = nil
	file_risk_v1_risk_proto_depIdxs = nil
}
