// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"riskcontral/internal/dao/internal"
)

// internalAggTx24HDao is internal type for wrapping internal DAO implements.
type internalAggTx24HDao = *internal.AggTx24HDao

// aggTx24HDao is the data access object for table agg_tx_24h.
// You can define custom methods on it to extend its functionality as you wish.
type aggTx24HDao struct {
	internalAggTx24HDao
}

var (
	// AggTx24H is globally public accessible object for table agg_tx_24h operations.
	AggTx24H = aggTx24HDao{
		internal.NewAggTx24HDao(),
	}
)

// Fill with you ideas below.
