// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"riskcontral/internal/dao/internal"
)

// internalAggNft24HDao is internal type for wrapping internal DAO implements.
type internalAggNft24HDao = *internal.AggNft24HDao

// aggNft24HDao is the data access object for table agg_nft_24h.
// You can define custom methods on it to extend its functionality as you wish.
type aggNft24HDao struct {
	internalAggNft24HDao
}

var (
	// AggNft24H is globally public accessible object for table agg_nft_24h operations.
	AggNft24H = aggNft24HDao{
		internal.NewAggNft24HDao(),
	}
)

// Fill with you ideas below.
