// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"riskcontral/internal/dao/internal"
)

// internalEthTxDao is internal type for wrapping internal DAO implements.
type internalEthTxDao = *internal.EthTxDao

// ethTxDao is the data access object for table eth_tx.
// You can define custom methods on it to extend its functionality as you wish.
type ethTxDao struct {
	internalEthTxDao
}

var (
	// EthTx is globally public accessible object for table eth_tx operations.
	EthTx = ethTxDao{
		internal.NewEthTxDao(),
	}
)

// Fill with you ideas below.
