// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"riskcontral/internal/dao/internal"
)

// internalScrapeLogsStatDao is internal type for wrapping internal DAO implements.
type internalScrapeLogsStatDao = *internal.ScrapeLogsStatDao

// scrapeLogsStatDao is the data access object for table scrape_logs_stat.
// You can define custom methods on it to extend its functionality as you wish.
type scrapeLogsStatDao struct {
	internalScrapeLogsStatDao
}

var (
	// ScrapeLogsStat is globally public accessible object for table scrape_logs_stat operations.
	ScrapeLogsStat = scrapeLogsStatDao{
		internal.NewScrapeLogsStatDao(),
	}
)

// Fill with you ideas below.
