// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"riskcontral/internal/dao/internal"
)

// internalScrapeLogStatDao is internal type for wrapping internal DAO implements.
type internalScrapeLogStatDao = *internal.ScrapeLogStatDao

// scrapeLogStatDao is the data access object for table scrape_log_stat.
// You can define custom methods on it to extend its functionality as you wish.
type scrapeLogStatDao struct {
	internalScrapeLogStatDao
}

var (
	// ScrapeLogStat is globally public accessible object for table scrape_log_stat operations.
	ScrapeLogStat = scrapeLogStatDao{
		internal.NewScrapeLogStatDao(),
	}
)

// Fill with you ideas below.
